version: "3.2"
services:
  rest:
    build: rest_server
    restart: on-failure
    scale: 3
    depends_on:
      - tarantool
      - mongo
      - rabbitmq
      - prometheus
      - sfu
    links:
      - rabbitmq
  sfu:
    build: sfu_server
    restart: on-failure
    depends_on:
      - rabbitmq
      - prometheus
    ports:
      - "2112:2112"
  tarantool:
    build:
      context: .
      dockerfile: Dockerfile.tarantool
    command: tarantool /usr/local/share/tarantool/tarantool_init.lua
    environment:
      TARANTOOL_USER_NAME: "tarantool"
      TARANTOOL_USER_PASSWORD: "tarantoolpwd"
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
  rabbitmq:
    image: "rabbitmq:3.8.9-management-alpine"
    ports:
      - 8080:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - "3005:3000"
  turn:
    build:
      context: .
      dockerfile: Dockerfile.turn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
      - "50000-50100:50000-50100"
    network_mode: "host"
  nginx:
    build: 
      context: .
      dockerfile: "Dockerfile.nginx"
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - turn 
      - rest
