apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  containers:
  - env:
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: secret
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    image: mongo
    name: mongo
    resources: {}
  restartPolicy: OnFailure
status: {}
