apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3.8.9-management-alpine
    livenessProbe:
      exec:
        command:
        - curl
        - -f
        - http://localhost:15672
      failureThreshold: 5
      periodSeconds: 30
      timeoutSeconds: 10
    name: rabbitmq
    ports:
    - containerPort: 15672
    resources: {}
  restartPolicy: OnFailure
status: {}
