apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/alex/bin/kompose convert -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 15672
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
