apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rest
  name: rest
spec:
  containers:
  - image: rest
    name: rest
    resources: {}
  restartPolicy: OnFailure
status: {}
