apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sfu
  name: sfu
spec:
  containers:
  - image: sfu
    name: sfu
    resources: {}
  restartPolicy: OnFailure
status: {}
