kind: Pod
apiVersion: v1
metadata:
  name: sfu
  labels:
    k8s-app: sfu
spec:
  containers:
    - name: sfu
      image: 'itcoursevideochat/sfu:latest'
      resources: {}
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status: {}
