name: E2E
on: [push]

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker-compose up -d
          sleep 1m
      - run: cd e2e && yarn install
      - run: cd e2e && yarn jest runWithSelenium.test.ts
    env:
      BROWSER: chrome
